language: python
python:
  - "2.7"
  - "3.4"
before_install:
 - "sudo apt-get install python-numpy libgdal1h gdal-bin libgdal-dev"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=pyskel -m py.test
after_success:
  - coveralls
sudo: false
