language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
  - sudo "mkdir /tmp/ramdisk; sudo chmod 777 /tmp/ramdisk; sudo mount -t tmpfs -o size=1M tmpfs /tmp/ramdisk/"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=riomucho -m py.test
after_success:
  - coveralls